project_id = "ygxnxxbxeflkvyxkwmwh"

[functions.analyze-message]
verify_jwt = false

[functions.list-conversations]
verify_jwt = false

[functions.loss-reason]
verify_jwt = false

[functions.register-sale]
verify_jwt = false
